### PR TITLE
Getting Travis CI to work

### LINKED ISSUE #2: Add travis and coveralls
Currently travis and coveralls don't find the package, we need to fix this.

### LINKED ISSUE #3: readthedocs
Setup readthedocs site.

### PR DESCRIPTION
**Pull request by StanczakDominik**
Closes #2.

Might close #3 along the way.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
It's not working yet, I'll get to it after breakfast

**Comment by StanczakDominik** [comment]
Okay, I think this is going to work. I can't tell for sure, though...

> How do you test that which has no tests?

**Comment by StanczakDominik** [comment]
Going to merge this for now, and if it breaks I'll come back to it.

**Comment by StanczakDominik** [comment]
I'd just like to note that these Travis logs are hilarious. It's two minutes of setup, and then comes the kicker...

```
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/PlasmaPy/SpectroscoPy, inifile: setup.cfg
collected 0 items 
========================= no tests ran in 0.44 seconds =========================
```

That's 0.44 seconds of awkward silence.

**Comment by lemmatum** [comment]
That's beautiful.
I've added a function so that Travis doesn't complain about the lack of work 😝

**Pull request merged**
